/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const ElLoading: typeof import('element-plus/es')['ElLoading']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const IEpCheck: typeof import('~icons/ep/check')['default']
  const IEpClose: typeof import('~icons/ep/close')['default']
  const IEpEdit: typeof import('~icons/ep/edit')['default']
  const IEpPicture: typeof import('~icons/ep/picture')['default']
  const IEpUpload: typeof import('~icons/ep/upload')['default']
}
